"""Golden fixtures for packages/math/src/ensemble/mixtureLogistic.ts.

PRML 14.5.2: a mixture of K independent binary logistic regression models with global
(input-independent) mixing coefficients, `p(t|phi) = sum_k pi_k y_k^t (1-y_k)^(1-t)` with
`y_k = sigmoid(w_k^T phi)` (14.45). The synthetic set below mirrors book figure 14.10: two
diagonal decision boundaries crossing the input space at different angles, generated by
actually sampling each point from one of two logistic components (latent `z_n ~
Categorical(pi)`, then `t_n ~ Bernoulli(y_{z_n})`), so a single logistic regression is a
provably bad fit (it can only draw one straight boundary) while the two-component mixture
recovers the generating process.

All reference numbers (responsibilities, log-likelihood, M-step) are computed independently
of the eventual TypeScript: responsibilities and log-likelihood directly from
`scipy.special.expit`, and the M-step's per-component weights via a fresh Newton-Raphson
loop written here (not imported from gen_weightedLogistic.py), run to a tight tolerance so it
lands at the same stationary point of a strictly convex weighted cross-entropy.
"""

import json
from pathlib import Path

import numpy as np
from scipy.special import expit

FIXTURES = Path(__file__).resolve().parent / "fixtures"
FIXTURES.mkdir(parents=True, exist_ok=True)

rng = np.random.default_rng(20260919)


def design_matrix(x1, x2):
    return np.stack([np.ones_like(x1), x1, x2], axis=1)


def mixture_log_terms(phi, t, weights, mixing):
    # log(pi_k) + t*log(y_k) + (1-t)*log(1-y_k), one row per point, one column per component.
    k = len(mixing)
    n = phi.shape[0]
    terms = np.zeros((n, k))
    for c in range(k):
        y = expit(phi @ weights[c])
        terms[:, c] = np.log(mixing[c]) + t * np.log(y) + (1 - t) * np.log(1 - y)
    return terms


def responsibilities_from_terms(terms):
    m = terms.max(axis=1, keepdims=True)
    unnorm = np.exp(terms - m)
    return unnorm / unnorm.sum(axis=1, keepdims=True)


def log_likelihood_from_terms(terms):
    m = terms.max(axis=1)
    return float(np.sum(m + np.log(np.sum(np.exp(terms - m[:, None]), axis=1))))


def weighted_newton_raphson(phi, t, w, tol=1e-13, max_iter=200):
    d = phi.shape[1]
    weights = np.zeros(d)
    for _ in range(max_iter):
        a = phi @ weights
        y = expit(a)
        r = w * y * (1 - y)
        r = np.maximum(r, 1e-10)
        hessian = phi.T @ (phi * r[:, None])
        gradient = phi.T @ (w * (y - t))
        step = np.linalg.solve(hessian, gradient)
        next_weights = weights - step
        if np.max(np.abs(next_weights - weights)) <= tol:
            weights = next_weights
            break
        weights = next_weights
    return weights


def mixture_m_step(phi, t, resp):
    n, k = resp.shape
    mixing = resp.mean(axis=0)
    weights = np.stack([weighted_newton_raphson(phi, t, resp[:, c]) for c in range(k)])
    return weights, mixing


# Two crossing diagonal boundaries: w_A ~ x1 - x2, w_B ~ -x1 - x2, so neither is a rotation
# of the other and no single line separates the union well.
TRUE_W = np.array([[0.2, 3.0, -3.0], [-0.3, -3.0, -3.0]])
TRUE_MIXING = np.array([0.5, 0.5])

N = 50
X1 = rng.normal(0.0, 1.0, N)
X2 = rng.normal(0.0, 1.0, N)
PHI = design_matrix(X1, X2)

Z = (
    rng.uniform(0.0, 1.0, N) >= TRUE_MIXING[0]
)  # False -> component 0, True -> component 1
Y_TRUE = np.where(Z, expit(PHI @ TRUE_W[1]), expit(PHI @ TRUE_W[0]))
T = (rng.uniform(0.0, 1.0, N) < Y_TRUE).astype(float)

cases = []

# Hand-chosen, plausible but not converged: same rough orientation as the true weights,
# smaller magnitude, and mixing shifted off 0.5/0.5.
HAND_WEIGHTS = np.array([[0.3, 2.0, -2.2], [-0.1, -2.4, -1.8]])
HAND_MIXING = np.array([0.4, 0.6])
hand_params = {"weights": HAND_WEIGHTS.tolist(), "mixing": HAND_MIXING.tolist()}

hand_terms = mixture_log_terms(PHI, T, HAND_WEIGHTS, HAND_MIXING)
hand_resp = responsibilities_from_terms(hand_terms)
hand_ll = log_likelihood_from_terms(hand_terms)

cases.append(
    {
        "fn": "mixtureLogisticResponsibilities",
        "design": PHI.tolist(),
        "targets": T.tolist(),
        "params": hand_params,
        "expected": hand_resp.tolist(),
    }
)
cases.append(
    {
        "fn": "mixtureLogisticLogLikelihood",
        "design": PHI.tolist(),
        "targets": T.tolist(),
        "params": hand_params,
        "expected": hand_ll,
    }
)

mstep_weights, mstep_mixing = mixture_m_step(PHI, T, hand_resp)
cases.append(
    {
        "fn": "mixtureLogisticMStep",
        "design": PHI.tolist(),
        "targets": T.tolist(),
        "responsibilities": hand_resp.tolist(),
        "expected": {
            "weights": mstep_weights.tolist(),
            "mixing": mstep_mixing.tolist(),
        },
    }
)

# A short EM trace from a fresh initial guess, hand-rolled E-step-then-M-step, 4 rounds.
init_weights = np.array([[0.0, 1.0, -1.0], [0.0, -1.0, -1.0]])
init_mixing = np.array([0.5, 0.5])

weights, mixing = init_weights.copy(), init_mixing.copy()
trace = []
for _ in range(4):
    terms = mixture_log_terms(PHI, T, weights, mixing)
    resp = responsibilities_from_terms(terms)
    ll_before = log_likelihood_from_terms(terms)
    weights, mixing = mixture_m_step(PHI, T, resp)
    trace.append(
        {
            "responsibilities": resp.tolist(),
            "logLikelihoodBeforeMStep": ll_before,
            "paramsAfterMStep": {
                "weights": weights.tolist(),
                "mixing": mixing.tolist(),
            },
        }
    )

cases.append(
    {
        "fn": "mixtureLogisticEmTrace",
        "design": PHI.tolist(),
        "targets": T.tolist(),
        "initialParams": {
            "weights": init_weights.tolist(),
            "mixing": init_mixing.tolist(),
        },
        "steps": 4,
        "expectedTrace": trace,
    }
)

fixture = {"cases": cases}
(FIXTURES / "mixtureLogistic.json").write_text(json.dumps(fixture, indent=2))
print(f"wrote {len(cases)} cases to mixtureLogistic.json")
