/**
 * Shared value types for `@prml/math`.
 *
 * Every public function takes and returns plain JavaScript arrays rather than a matrix
 * class, so that golden fixtures generated by numpy serialise to JSON and compare
 * structurally with no adapter layer in between. `ml-matrix` is an implementation
 * detail of `linalg/` and must not appear in any exported signature.
 *
 * Matrices are row-major and rectangular: `m[i][j]` is row `i`, column `j`. Functions
 * may assume rectangularity and are not required to validate it.
 */

export type Vec = readonly number[];

export type Mat = readonly (readonly number[])[];

/**
 * A seeded pseudo-random source. Every stochastic function in this package takes an
 * `Rng` explicitly; none reads `Math.random`, because reproducible figures and golden
 * tests both depend on the caller owning the seed.
 */
export interface Rng {
  /** Raw 32-bit output. */
  nextUint32(): number;
  /** Uniform on [0, 1). */
  next(): number;
  /**
   * An independent stream from the same seed. Two forks with different `streamId`
   * values never overlap, so a widget can give each of its panels its own stream
   * without one panel's sample count perturbing another's.
   */
  fork(streamId: number): Rng;
}

/**
 * A parametric density, packaged so that generic code (the distribution explorer,
 * the mixture fitters) can iterate over families uniformly. Individual modules also
 * export their functions free-standing; this object is assembled from those.
 *
 * `X` is the sample type (number, or `Vec`, or `Mat` for Wishart) and `P` the
 * parameter record.
 */
export interface Family<X, P> {
  readonly name: string;
  readonly logPdf: (x: X, p: P) => number;
  readonly pdf: (x: X, p: P) => number;
  readonly sample: (rng: Rng, p: P) => X;
  readonly mean: (p: P) => X;
}

/**
 * Thrown by every stub in this package before it is implemented. A test that fails
 * with this is a task not yet done; a test that fails any other way is a bug.
 */
export class NotImplemented extends Error {
  constructor(what: string) {
    super(`@prml/math: ${what} is not implemented yet`);
    this.name = 'NotImplemented';
  }
}
