#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import {
  DARK,
  DIVERGING,
  LAYOUT,
  LIGHT,
  MOTION,
  RADIUS,
  SEQUENTIAL,
  SERIES,
  SHADOW,
  SPACE,
  TYPE,
  Z,
  kebab,
} from '../packages/ui/src/tokens.ts';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../packages/ui/src/tokens.css');

const scheme = (colors) =>
  Object.entries(colors)
    .map(([role, value]) => `  --prml-color-${kebab(role)}: ${value};`)
    .join('\n');

const list = (prefix, values) =>
  values.map((v, i) => `  --prml-${prefix}-${i}: ${v};`).join('\n');

const record = (prefix, values) =>
  Object.entries(values)
    .map(([k, v]) => `  --prml-${prefix}-${kebab(k)}: ${v};`)
    .join('\n');

const css = `/* Generated by scripts/tokens-build.mjs from packages/ui/src/tokens.ts. Do not edit. */

:root {
  color-scheme: light dark;

${scheme(LIGHT)}

${list('series', [...SERIES])}

${list('sequential', [...SEQUENTIAL])}

${list('diverging', [...DIVERGING])}

${list('space', [...SPACE].map((n) => `${n}px`))}

  --prml-font-serif: ${TYPE.serif};
  --prml-font-sans: ${TYPE.sans};
  --prml-font-mono: ${TYPE.mono};

${record('text', TYPE.scale)}

${record('leading', TYPE.leading)}

${record('weight', TYPE.weight)}

${record('radius', RADIUS)}

${record('shadow', SHADOW)}

${record('motion', MOTION)}

${record('layout', LAYOUT)}

${record('z', Z)}
}

[data-theme='dark'] {
${scheme(DARK)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${scheme(DARK)
  .split('\n')
  .map((l) => `  ${l}`)
  .join('\n')}
  }
}
`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(out, 'utf8');
  } catch {
    console.error('tokens.css is missing. Run `pnpm tokens:build`.');
    process.exit(1);
  }
  if (current !== css) {
    console.error('tokens.css is stale. Run `pnpm tokens:build`.');
    process.exit(1);
  }
  console.log('tokens.css is current.');
} else {
  writeFileSync(out, css);
  console.log(`wrote ${out}`);
}
